### ISSUE TITLE
Seem to get stuck on "Try The Game"

### ISSUE THREAD

**Issue by frankcarey** [gdquest-demos/godot-tours-101-the-godot-editor#3]
Just downloaded it today. Imported with godot 4.2.1 on windows 11, which seemed to work fine. I can start the game, but when I close it (via F8 or closing it) the checkbox never completes and there doesn't seem to be a way to skip. I'd suggest adding a skip button as a backup option.

Thanks for making this btw - I'm going to be using it for my university course and will be looking into the general tooling to make my own lessons for them as well. Kudos!

![image](https://github.com/gdquest-demos/godot-tours-101-the-godot-editor/assets/377330/b4a5bf32-87ed-4e64-b308-e6306a01ff92)

**Comment by NathanLovato** [comment]
According to your screenshot, you're using the mono build of Godot. As mentioned in the readme, the tour only support the standard version. I invite you to download and open it with the standard Godot editor.
