### ISSUE TITLE
project crashes

### ISSUE THREAD

**Issue by kingkk0310** [gdquest-demos/godot-tours-101-the-godot-editor#7]
the project crashes/closes as soon as i hit edit in the godot project manager. is there a fix for this? or any alternatives that may work

**Comment by turkeydonkey** [comment]
> the project crashes/closes as soon as i hit edit in the godot project manager. is there a fix for this? or any alternatives that may work

Have you cloned the most recent version from the repo and tried importing that? I had the same problem, and while I got the same script compilation error at first, godot restarted itself and completed the import process, and the tour seems to be working. The release .zip might also work if it's current, I just find it easier (and much faster) to use git.

**Comment by NathanLovato** [comment]
This should be fixed with f2d3ffd4a6e7ded8f7b53421f156a90a926c8ccb
