### ISSUE TITLE
The editor crashes after opening the project

### ISSUE THREAD

**Issue by hakanguclu** [gdquest-demos/godot-tours-101-the-godot-editor#8]
After I download the project, import it to the Project Manager, and click "Edit", the editor opens but it crashes in a couple of seconds.

Here's a short screen recording of the issue:
https://github.com/user-attachments/assets/e582409e-35c5-4f61-a49a-c2821036c422

Godot version: 4.3
OS: Windows 11

**Comment by NathanLovato** [comment]
I think you may not have the latest version. Could you please try deleting your copy of the project and downloading this one? https://github.com/gdquest-demos/godot-tours-101-the-godot-editor/releases/tag/1.1.1

It was released yesterday afternoon. Could you give it a try and let me know if it works better? You will need to manually activate the plugin following the instructions here: https://www.gdquest.com/tutorial/godot/learning-paths/godot-tours-101/

**Comment by hakanguclu** [comment]
That works perfectly. Thank you!

**Comment by NathanLovato** [comment]
Great, thanks for testing and confirming!
